version: '3.8'

services:
  # =====================================
  # api
  # =====================================
  node-sample-api:
    container_name: 'node-sample-api'
    build:
      context: .
    image: node-sample-api-image
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - sample-db
  # =====================================
  # db
  # =====================================
  sample-db:
    image: postgres:latest
    platform: linux/amd64
    container_name: 'sample-db'
    env_file:
      - .env
    environment:
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=C'
      POSTGRES_DB: sample_db
    volumes:
      - ./db/pgql_db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5434:5432'