version: '3.8'
services:
  ecs-fargate-cdk:
    image: mysql:8.0.36-bookworm
    platform: linux/amd64
    container_name: ecs-fargate-cdk-mysql
    environment:
      MYSQL_USER: default
      MYSQL_PASSWORD: default
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_db
    volumes:
      - ./mysql_devmode:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
